---
collections:
  - name: a10.acos_cli
  - name: amazon.aws
  - name: ansible.controller
  - name: ansible.netcommon
  - name: ansible.posix
  - name: ansible.utils
  - name: ansible.windows
  - name: arista.avd
  - name: arista.cvp
# sets paramiko higher than 12 other collections
#  - name: arista.dmf
  - name: arista.eos
  - name: awx.awx
  - name: azure.azcollection
  - name: check_point.gaia
  - name: check_point.mgmt
  - name: chocolatey.chocolatey
  - name: cisco.aci
  - name: cisco.asa
  - name: cisco.dcnm
  - name: cisco.dnac
  - name: cisco.intersight
  - name: cisco.ios
  - name: cisco.iosxr
  - name: cisco.ise
  - name: cisco.mso
  - name: cisco.nxos
#  - name: cisco.meraki
#  - name: cisco.nso
#  - name: cisco.ucs
  - name: cloud.common
  - name: cloud.terraform
  - name: cloudscale_ch.cloud
  - name: community.aws
  - name: community.azure
  - name: community.ciscosmb
  - name: community.crypto
  - name: community.digitalocean
  - name: community.dns
  - name: community.docker
  - name: community.fortios
  - name: community.general
  - name: community.google
  - name: community.grafana
  - name: community.hashi_vault
  - name: community.hrobot
  - name: community.libvirt
  - name: community.mongodb
  - name: community.mysql
  - name: community.network
  - name: community.okd
  - name: community.postgresql
  - name: community.proxysql
  - name: community.rabbitmq
  - name: community.routeros
  - name: community.sap
  - name: community.sap_libs
  - name: community.skydive
  - name: community.sops
  - name: community.vmware
  - name: community.windows
  - name: community.zabbix
  - name: confluent.platform
  - name: containers.podman
  - name: crowdstrike.falcon
  - name: cyberark.conjur
  - name: cyberark.pas
  - name: datadog.dd
  - name: delinea.ss
  - name: dellemc.enterprise_sonic
  - name: dellemc.openmanage
  - name: dellemc.os10
  - name: dellemc.powerflex
  - name: dellemc.powerscale
  - name: dellemc.powerstore
  - name: dellemc.unity
  - name: dynatrace.event_driven_ansible
  - name: enfence.powerha_aix
  - name: f5networks.f5_bigip
  - name: f5networks.f5_modules
  - name: f5networks.f5os
  - name: fortinet.fortianalyzer
  - name: fortinet.fortiflexvm
  - name: fortinet.fortimanager
  - name: fortinet.fortios
  - name: fortinet.fortiswitch
  - name: frr.frr
  - name: gluster.gluster
  - name: google.cloud
  - name: grafana.grafana
  - name: hetzner.hcloud
  - name: hpe.nimble
  - name: ibm.power_aix
  - name: ibm.power_hmc
  - name: ibm.qradar
  - name: ibm.spectrum_virtualize
  - name: ibm.storage_virtualize
# Sets explicit python packages that break other collections
#  - name: ibm.turbonomic_eda
  - name: infinidat.infinibox
  - name: infoblox.nios_modules
  - name: infra.ah_configuration
  - name: infra.controller_configuration
  - name: infra.ee_utilities
  - name: inspur.ispim
  - name: inspur.sm
  - name: junipernetworks.junos
  - name: kubernetes.core
  - name: logicmonitor.integration
  - name: lowlydba.sqlserver
  - name: microsoft.ad
  - name: netapp.aws
  - name: netapp.azure
  - name: netapp.cloudmanager
  - name: netapp.elementsw
  - name: netapp.ontap
  - name: netapp.storagegrid
  - name: netapp.um_info
  - name: netapp_eseries.santricity
  - name: netbox.netbox
  - name: ngine_io.cloudstack
  - name: ngine_io.exoscale
  - name: ngine_io.vultr
  - name: nutanix.ncp
  - name: nvidia.nvue
  - name: onepassword.connect
  - name: openstack.cloud
  - name: openvswitch.openvswitch
  - name: ovirt.ovirt
  - name: paloaltonetworks.panos
  - name: purestorage.flasharray
  - name: purestorage.flashblade
  - name: purestorage.fusion
  - name: purestorage.pure1
  - name: radware.radware_alteon
  - name: redhat.amq_broker
  - name: redhat.data_grid
  - name: redhat.eap
  - name: redhat.insights_eda
  - name: redhat.jbcs
  - name: redhat.jws
  - name: redhat.openshift
  - name: redhat.redhat_csp_download
  - name: redhat.rhel_idm
  - name: redhat.rhel_system_roles
  - name: redhat.runtimes_common
  - name: redhat.satellite_operations
  - name: redhat.sso
  - name: redhat_cop.tower_configuration
  - name: scale_computing.hypercore
  - name: sensu.sensu_go
  - name: servicenow.itsm
  - name: splunk.es
  - name: t_systems_mms.icinga_director
  - name: telekom_mms.icinga_director
  - name: theforeman.foreman
  - name: trilio.trilio_kubernetes
  - name: venafi.machine_identity
  - name: vmware.vmware_rest
  - name: vultr.cloud
# sets explicit python packages that break other collections
#  - name: vyos.vyos
  - name: wti.remote